### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by shatl** [alphacloud/Autofac.Extras.Quartz#65]
Review and fix Autofac.Extras.Quartz.Tests.ScopeTrackerTests.ShouldDisposeScopeAfterJobCompletion

```) Error : Autofac.Extras.Quartz.Tests.ScopeTrackerTests.ShouldDisposeScopeAfterJobCompletion
Quartz.SchedulerException : The Scheduler has been Shutdown.
   at Quartz.Core.QuartzScheduler.ValidateState()
   at Quartz.Core.QuartzScheduler.<ScheduleJob>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Autofac.Extras.Quartz.Tests.ScopeTrackerTests.<ShouldDisposeScopeAfterJobCompletion>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)
```

**Comment by shatl** [comment]
Fixed in #68 (don't run tests in parallel)
